// Mocks generated by Mockito 5.4.6 from annotations
// in ngonnest_app/test/widgets/cloud_import_dialog_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:ngonnest_app/services/cloud_import_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeImportResult_0 extends _i1.SmartFake implements _i2.ImportResult {
  _FakeImportResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CloudImportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCloudImportService extends _i1.Mock
    implements _i2.CloudImportService {
  MockCloudImportService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> checkCloudData() =>
      (super.noSuchMethod(
            Invocation.method(#checkCloudData, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i2.ImportResult> importAllData() =>
      (super.noSuchMethod(
            Invocation.method(#importAllData, []),
            returnValue: _i3.Future<_i2.ImportResult>.value(
              _FakeImportResult_0(this, Invocation.method(#importAllData, [])),
            ),
          )
          as _i3.Future<_i2.ImportResult>);

  @override
  Map<String, dynamic> mapHouseholdToLocal(Map<String, dynamic>? household) =>
      (super.noSuchMethod(
            Invocation.method(#mapHouseholdToLocal, [household]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  Map<String, dynamic> mapProductToLocal(Map<String, dynamic>? product) =>
      (super.noSuchMethod(
            Invocation.method(#mapProductToLocal, [product]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  Map<String, dynamic> mapBudgetCategoryToLocal(Map<String, dynamic>? budget) =>
      (super.noSuchMethod(
            Invocation.method(#mapBudgetCategoryToLocal, [budget]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  Map<String, dynamic> mapPurchaseToLocal(Map<String, dynamic>? purchase) =>
      (super.noSuchMethod(
            Invocation.method(#mapPurchaseToLocal, [purchase]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
