// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDykOMJesT6-Z_bLdKhBnuzgKJMU1do5bc',
    appId: '1:323254445931:web:d556d91661c0ad0f260e2e',
    messagingSenderId: '323254445931',
    projectId: 'ngonnest-analytics',
    authDomain: 'ngonnest-analytics.firebaseapp.com',
    storageBucket: 'ngonnest-analytics.firebasestorage.app',
    measurementId: 'G-11RQM4MX3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY5SeA8VXMmVqAWpEkigo2hnvBBBYJJco',
    appId: '1:323254445931:android:706bd1ffba4cd9e0260e2e',
    messagingSenderId: '323254445931',
    projectId: 'ngonnest-analytics',
    storageBucket: 'ngonnest-analytics.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkt-GU3f18JDUAhoufiwdBwzxMkOhOpy4',
    appId: '1:323254445931:ios:8ec56daeef37bd97260e2e',
    messagingSenderId: '323254445931',
    projectId: 'ngonnest-analytics',
    storageBucket: 'ngonnest-analytics.firebasestorage.app',
    iosBundleId: 'com.example.ngonnestApp',
  );
}
