// Mocks generated by Mockito 5.4.6 from annotations
// in ngonnest_app/test/integration/task5_budget_notifications_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:connectivity_plus/connectivity_plus.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:ngonnest_app/services/analytics_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i2.AnalyticsService {
  MockAnalyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logEvent(
    String? eventName, {
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #logEvent,
              [eventName],
              {#parameters: parameters},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setUserProperty(String? name, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setUserProperty, [name, value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logOnboardingStarted() =>
      (super.noSuchMethod(
            Invocation.method(#logOnboardingStarted, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logOnboardingCompleted() =>
      (super.noSuchMethod(
            Invocation.method(#logOnboardingCompleted, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logCoreAction(
    String? actionType, {
    Map<String, Object>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #logCoreAction,
              [actionType],
              {#additionalParams: additionalParams},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logFlowStarted(String? flowName) =>
      (super.noSuchMethod(
            Invocation.method(#logFlowStarted, [flowName]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logFlowCompleted(
    String? flowName, {
    Map<String, Object>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #logFlowCompleted,
              [flowName],
              {#additionalParams: additionalParams},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logFlowAbandoned(String? flowName, {String? reason}) =>
      (super.noSuchMethod(
            Invocation.method(#logFlowAbandoned, [flowName], {#reason: reason}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logOfflineSessionStarted() =>
      (super.noSuchMethod(
            Invocation.method(#logOfflineSessionStarted, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logOfflineSessionEnded() =>
      (super.noSuchMethod(
            Invocation.method(#logOfflineSessionEnded, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logMigrationAttempt(int? fromVersion, int? toVersion) =>
      (super.noSuchMethod(
            Invocation.method(#logMigrationAttempt, [fromVersion, toVersion]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logMigrationSuccess(
    int? fromVersion,
    int? toVersion,
    int? durationMs,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#logMigrationSuccess, [
              fromVersion,
              toVersion,
              durationMs,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logMigrationFailure(
    int? fromVersion,
    int? toVersion,
    String? errorCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#logMigrationFailure, [
              fromVersion,
              toVersion,
              errorCode,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logSyncAttemptStarted() =>
      (super.noSuchMethod(
            Invocation.method(#logSyncAttemptStarted, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logSyncAttemptEnded(bool? success, {String? errorCode}) =>
      (super.noSuchMethod(
            Invocation.method(
              #logSyncAttemptEnded,
              [success],
              {#errorCode: errorCode},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logDatabaseOperation(
    String? operationType,
    int? durationMs,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#logDatabaseOperation, [
              operationType,
              durationMs,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logFeatureFirstUse(String? featureName) =>
      (super.noSuchMethod(
            Invocation.method(#logFeatureFirstUse, [featureName]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logEmptyStateCTAClicked(String? emptyStateScreen) =>
      (super.noSuchMethod(
            Invocation.method(#logEmptyStateCTAClicked, [emptyStateScreen]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logSettingChanged(String? settingName, String? newValue) =>
      (super.noSuchMethod(
            Invocation.method(#logSettingChanged, [settingName, newValue]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logAlertFeedback(String? alertId, String? feedbackValue) =>
      (super.noSuchMethod(
            Invocation.method(#logAlertFeedback, [alertId, feedbackValue]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setHouseholdProfile({
    required int? householdSize,
    String? householdType,
    String? primaryLanguage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setHouseholdProfile, [], {
              #householdSize: householdSize,
              #householdType: householdType,
              #primaryLanguage: primaryLanguage,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> trackConnectivityChange(_i4.ConnectivityResult? result) =>
      (super.noSuchMethod(
            Invocation.method(#trackConnectivityChange, [result]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logItemAction(
    String? action, {
    Map<String, Object>? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logItemAction, [action], {#params: params}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logInventoryAction(
    String? action, {
    Map<String, Object>? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logInventoryAction, [action], {#params: params}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logAlertAction(
    String? action, {
    Map<String, Object>? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logAlertAction, [action], {#params: params}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logBudgetAction(
    String? action, {
    Map<String, Object>? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logBudgetAction, [action], {#params: params}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
