// Mocks generated by Mockito 5.4.6 from annotations
// in ngonnest_app/test/screens/budget_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i6;

import 'package:connectivity_plus/connectivity_plus.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:ngonnest_app/models/budget_category.dart' as _i4;
import 'package:ngonnest_app/models/foyer.dart' as _i10;
import 'package:ngonnest_app/providers/foyer_provider.dart' as _i9;
import 'package:ngonnest_app/services/analytics_service.dart' as _i7;
import 'package:ngonnest_app/services/budget_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [BudgetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBudgetService extends _i1.Mock implements _i2.BudgetService {
  MockBudgetService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i3.Future<List<_i4.BudgetCategory>> getBudgetCategories({String? month}) =>
      (super.noSuchMethod(
            Invocation.method(#getBudgetCategories, [], {#month: month}),
            returnValue: _i3.Future<List<_i4.BudgetCategory>>.value(
              <_i4.BudgetCategory>[],
            ),
          )
          as _i3.Future<List<_i4.BudgetCategory>>);

  @override
  _i3.Future<String> createBudgetCategory(
    _i4.BudgetCategory? category, {
    bool? notify = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createBudgetCategory,
              [category],
              {#notify: notify},
            ),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(
                  #createBudgetCategory,
                  [category],
                  {#notify: notify},
                ),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<int> updateBudgetCategory(
    _i4.BudgetCategory? category, {
    bool? notify = true,
    _i4.BudgetCategory? oldCategory,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateBudgetCategory,
              [category],
              {#notify: notify, #oldCategory: oldCategory},
            ),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<String> deleteBudgetCategory(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBudgetCategory, [id]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#deleteBudgetCategory, [id]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> syncBudgetWithPurchases(String? idFoyer, {String? month}) =>
      (super.noSuchMethod(
            Invocation.method(
              #syncBudgetWithPurchases,
              [idFoyer],
              {#month: month},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getMonthlyExpenseHistory(
    String? idFoyer,
    String? categoryName, {
    int? monthsBack = 12,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getMonthlyExpenseHistory,
              [idFoyer, categoryName],
              {#monthsBack: monthsBack},
            ),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<void> initializeDefaultCategories({String? month}) =>
      (super.noSuchMethod(
            Invocation.method(#initializeDefaultCategories, [], {
              #month: month,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> checkBudgetAlertsAfterPurchase(
    String? idFoyer,
    String? categoryName, {
    String? month,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #checkBudgetAlertsAfterPurchase,
              [idFoyer, categoryName],
              {#month: month},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> recalculateCategoryBudgets(
    String? idFoyer,
    double? newTotalBudget, {
    String? month,
    double? oldTotalBudget,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #recalculateCategoryBudgets,
              [idFoyer, newTotalBudget],
              {#month: month, #oldTotalBudget: oldTotalBudget},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> getBudgetSummary({String? month}) =>
      (super.noSuchMethod(
            Invocation.method(#getBudgetSummary, [], {#month: month}),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, double>> calculateRecommendedBudget(String? idFoyer) =>
      (super.noSuchMethod(
            Invocation.method(#calculateRecommendedBudget, [idFoyer]),
            returnValue: _i3.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i3.Future<Map<String, double>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> generateSavingsTips(
    String? idFoyer, {
    String? month,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateSavingsTips, [idFoyer], {#month: month}),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<Map<String, dynamic>> getSpendingHistory(
    String? idFoyer, {
    int? monthsBack = 6,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getSpendingHistory,
              [idFoyer],
              {#monthsBack: monthsBack},
            ),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> initializeRecommendedBudgets(
    String? idFoyer, {
    String? month,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #initializeRecommendedBudgets,
              [idFoyer],
              {#month: month},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i7.AnalyticsService {
  MockAnalyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logEvent(
    String? eventName, {
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #logEvent,
              [eventName],
              {#parameters: parameters},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setUserProperty(String? name, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setUserProperty, [name, value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logOnboardingStarted() =>
      (super.noSuchMethod(
            Invocation.method(#logOnboardingStarted, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logOnboardingCompleted() =>
      (super.noSuchMethod(
            Invocation.method(#logOnboardingCompleted, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logCoreAction(
    String? actionType, {
    Map<String, Object>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #logCoreAction,
              [actionType],
              {#additionalParams: additionalParams},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logFlowStarted(String? flowName) =>
      (super.noSuchMethod(
            Invocation.method(#logFlowStarted, [flowName]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logFlowCompleted(
    String? flowName, {
    Map<String, Object>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #logFlowCompleted,
              [flowName],
              {#additionalParams: additionalParams},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logFlowAbandoned(String? flowName, {String? reason}) =>
      (super.noSuchMethod(
            Invocation.method(#logFlowAbandoned, [flowName], {#reason: reason}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logOfflineSessionStarted() =>
      (super.noSuchMethod(
            Invocation.method(#logOfflineSessionStarted, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logOfflineSessionEnded() =>
      (super.noSuchMethod(
            Invocation.method(#logOfflineSessionEnded, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logMigrationAttempt(int? fromVersion, int? toVersion) =>
      (super.noSuchMethod(
            Invocation.method(#logMigrationAttempt, [fromVersion, toVersion]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logMigrationSuccess(
    int? fromVersion,
    int? toVersion,
    int? durationMs,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#logMigrationSuccess, [
              fromVersion,
              toVersion,
              durationMs,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logMigrationFailure(
    int? fromVersion,
    int? toVersion,
    String? errorCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#logMigrationFailure, [
              fromVersion,
              toVersion,
              errorCode,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logSyncAttemptStarted() =>
      (super.noSuchMethod(
            Invocation.method(#logSyncAttemptStarted, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logSyncAttemptEnded(bool? success, {String? errorCode}) =>
      (super.noSuchMethod(
            Invocation.method(
              #logSyncAttemptEnded,
              [success],
              {#errorCode: errorCode},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logDatabaseOperation(
    String? operationType,
    int? durationMs,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#logDatabaseOperation, [
              operationType,
              durationMs,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logFeatureFirstUse(String? featureName) =>
      (super.noSuchMethod(
            Invocation.method(#logFeatureFirstUse, [featureName]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logEmptyStateCTAClicked(String? emptyStateScreen) =>
      (super.noSuchMethod(
            Invocation.method(#logEmptyStateCTAClicked, [emptyStateScreen]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logSettingChanged(String? settingName, String? newValue) =>
      (super.noSuchMethod(
            Invocation.method(#logSettingChanged, [settingName, newValue]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logAlertFeedback(String? alertId, String? feedbackValue) =>
      (super.noSuchMethod(
            Invocation.method(#logAlertFeedback, [alertId, feedbackValue]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setHouseholdProfile({
    required int? householdSize,
    String? householdType,
    String? primaryLanguage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setHouseholdProfile, [], {
              #householdSize: householdSize,
              #householdType: householdType,
              #primaryLanguage: primaryLanguage,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> trackConnectivityChange(_i8.ConnectivityResult? result) =>
      (super.noSuchMethod(
            Invocation.method(#trackConnectivityChange, [result]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logItemAction(
    String? action, {
    Map<String, Object>? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logItemAction, [action], {#params: params}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logInventoryAction(
    String? action, {
    Map<String, Object>? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logInventoryAction, [action], {#params: params}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logAlertAction(
    String? action, {
    Map<String, Object>? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logAlertAction, [action], {#params: params}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logBudgetAction(
    String? action, {
    Map<String, Object>? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logBudgetAction, [action], {#params: params}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [FoyerProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockFoyerProvider extends _i1.Mock implements _i9.FoyerProvider {
  MockFoyerProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void setFoyer(_i10.Foyer? foyer) => super.noSuchMethod(
    Invocation.method(#setFoyer, [foyer]),
    returnValueForMissingStub: null,
  );

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
