// Mocks generated by Mockito 5.4.6 from annotations
// in ngonnest_app/test/screens/settings_budget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i15;

import 'package:flutter/material.dart' as _i17;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:ngonnest_app/models/alert.dart' as _i9;
import 'package:ngonnest_app/models/alert_state.dart' as _i11;
import 'package:ngonnest_app/models/budget_category.dart' as _i14;
import 'package:ngonnest_app/models/foyer.dart' as _i6;
import 'package:ngonnest_app/models/objet.dart' as _i8;
import 'package:ngonnest_app/models/product_price.dart' as _i10;
import 'package:ngonnest_app/models/userprofile.dart' as _i19;
import 'package:ngonnest_app/repository/foyer_repository.dart' as _i12;
import 'package:ngonnest_app/services/auth_service.dart' as _i18;
import 'package:ngonnest_app/services/budget_service.dart' as _i13;
import 'package:ngonnest_app/services/database_service.dart' as _i4;
import 'package:ngonnest_app/services/sync_service.dart' as _i16;
import 'package:sqflite/sqflite.dart' as _i2;
import 'package:supabase_flutter/supabase_flutter.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResponse_1 extends _i1.SmartFake implements _i3.AuthResponse {
  _FakeAuthResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i4.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i5.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i5.Future<_i2.Database>);

  @override
  _i5.Future<_i6.Foyer?> getFoyer() =>
      (super.noSuchMethod(
            Invocation.method(#getFoyer, []),
            returnValue: _i5.Future<_i6.Foyer?>.value(),
          )
          as _i5.Future<_i6.Foyer?>);

  @override
  _i5.Future<String> insertFoyer(_i6.Foyer? foyer) =>
      (super.noSuchMethod(
            Invocation.method(#insertFoyer, [foyer]),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#insertFoyer, [foyer]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<int> updateFoyer(_i6.Foyer? foyer) =>
      (super.noSuchMethod(
            Invocation.method(#updateFoyer, [foyer]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> deleteFoyer(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFoyer, [id]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<List<_i8.Objet>> getObjets({int? idFoyer, _i8.TypeObjet? type}) =>
      (super.noSuchMethod(
            Invocation.method(#getObjets, [], {#idFoyer: idFoyer, #type: type}),
            returnValue: _i5.Future<List<_i8.Objet>>.value(<_i8.Objet>[]),
          )
          as _i5.Future<List<_i8.Objet>>);

  @override
  _i5.Future<_i8.Objet?> getObjet(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getObjet, [id]),
            returnValue: _i5.Future<_i8.Objet?>.value(),
          )
          as _i5.Future<_i8.Objet?>);

  @override
  _i5.Future<int> insertObjet(_i8.Objet? objet) =>
      (super.noSuchMethod(
            Invocation.method(#insertObjet, [objet]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> updateObjet(_i8.Objet? objet) =>
      (super.noSuchMethod(
            Invocation.method(#updateObjet, [objet]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> deleteObjet(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteObjet, [id]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> getTotalObjetCount(int? idFoyer) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalObjetCount, [idFoyer]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> getExpiringSoonObjetCount(int? idFoyer) =>
      (super.noSuchMethod(
            Invocation.method(#getExpiringSoonObjetCount, [idFoyer]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<List<_i8.Objet>> getObjetsWithAlerts(int? idFoyer) =>
      (super.noSuchMethod(
            Invocation.method(#getObjetsWithAlerts, [idFoyer]),
            returnValue: _i5.Future<List<_i8.Objet>>.value(<_i8.Objet>[]),
          )
          as _i5.Future<List<_i8.Objet>>);

  @override
  _i5.Future<List<_i8.Objet>> searchObjets({
    required String? query,
    int? idFoyer,
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchObjets, [], {
              #query: query,
              #idFoyer: idFoyer,
              #limit: limit,
            }),
            returnValue: _i5.Future<List<_i8.Objet>>.value(<_i8.Objet>[]),
          )
          as _i5.Future<List<_i8.Objet>>);

  @override
  _i5.Future<Map<String, double>> getBudgetMensuel(int? idFoyer) =>
      (super.noSuchMethod(
            Invocation.method(#getBudgetMensuel, [idFoyer]),
            returnValue: _i5.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i5.Future<Map<String, double>>);

  @override
  _i5.Future<List<_i9.Alert>> getAlerts({int? idFoyer, bool? unreadOnly}) =>
      (super.noSuchMethod(
            Invocation.method(#getAlerts, [], {
              #idFoyer: idFoyer,
              #unreadOnly: unreadOnly,
            }),
            returnValue: _i5.Future<List<_i9.Alert>>.value(<_i9.Alert>[]),
          )
          as _i5.Future<List<_i9.Alert>>);

  @override
  _i5.Future<_i9.Alert?> getAlert(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAlert, [id]),
            returnValue: _i5.Future<_i9.Alert?>.value(),
          )
          as _i5.Future<_i9.Alert?>);

  @override
  _i5.Future<int> insertAlert(_i9.Alert? alert) =>
      (super.noSuchMethod(
            Invocation.method(#insertAlert, [alert]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> updateAlert(_i9.Alert? alert) =>
      (super.noSuchMethod(
            Invocation.method(#updateAlert, [alert]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> deleteAlert(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAlert, [id]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> insertObjetWithAlerts(_i8.Objet? objet, int? idFoyer) =>
      (super.noSuchMethod(
            Invocation.method(#insertObjetWithAlerts, [objet, idFoyer]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> markAlertAsRead(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#markAlertAsRead, [id]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> deleteAllReadAlerts(int? idFoyer) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllReadAlerts, [idFoyer]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<Map<int, Map<String, bool>>> getAlertStates() =>
      (super.noSuchMethod(
            Invocation.method(#getAlertStates, []),
            returnValue: _i5.Future<Map<int, Map<String, bool>>>.value(
              <int, Map<String, bool>>{},
            ),
          )
          as _i5.Future<Map<int, Map<String, bool>>>);

  @override
  _i5.Future<void> generateAlerts(int? idFoyer) =>
      (super.noSuchMethod(
            Invocation.method(#generateAlerts, [idFoyer]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> isConnectionValid() =>
      (super.noSuchMethod(
            Invocation.method(#isConnectionValid, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  Map<String, dynamic> getConnectionStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getConnectionStatus, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i5.Future<void> debugTableStructure() =>
      (super.noSuchMethod(
            Invocation.method(#debugTableStructure, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearAllData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllData, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> forceReinitialize() =>
      (super.noSuchMethod(
            Invocation.method(#forceReinitialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i10.ProductPrice?> searchPrice(
    String? productName, {
    String? countryCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchPrice,
              [productName],
              {#countryCode: countryCode},
            ),
            returnValue: _i5.Future<_i10.ProductPrice?>.value(),
          )
          as _i5.Future<_i10.ProductPrice?>);

  @override
  _i5.Future<List<_i10.ProductPrice>> getAllPrices({String? countryCode}) =>
      (super.noSuchMethod(
            Invocation.method(#getAllPrices, [], {#countryCode: countryCode}),
            returnValue: _i5.Future<List<_i10.ProductPrice>>.value(
              <_i10.ProductPrice>[],
            ),
          )
          as _i5.Future<List<_i10.ProductPrice>>);

  @override
  _i5.Future<void> upsertPrice(_i10.ProductPrice? price) =>
      (super.noSuchMethod(
            Invocation.method(#upsertPrice, [price]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int> importPricesFromCSV(String? csvContent) =>
      (super.noSuchMethod(
            Invocation.method(#importPricesFromCSV, [csvContent]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> saveAlertState(_i11.AlertState? state) =>
      (super.noSuchMethod(
            Invocation.method(#saveAlertState, [state]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i11.AlertState?> getAlertState(int? alertId) =>
      (super.noSuchMethod(
            Invocation.method(#getAlertState, [alertId]),
            returnValue: _i5.Future<_i11.AlertState?>.value(),
          )
          as _i5.Future<_i11.AlertState?>);

  @override
  _i5.Future<Map<int, _i11.AlertState>> getAllAlertStates() =>
      (super.noSuchMethod(
            Invocation.method(#getAllAlertStates, []),
            returnValue: _i5.Future<Map<int, _i11.AlertState>>.value(
              <int, _i11.AlertState>{},
            ),
          )
          as _i5.Future<Map<int, _i11.AlertState>>);
}

/// A class which mocks [FoyerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFoyerRepository extends _i1.Mock implements _i12.FoyerRepository {
  MockFoyerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.Foyer?> get() =>
      (super.noSuchMethod(
            Invocation.method(#get, []),
            returnValue: _i5.Future<_i6.Foyer?>.value(),
          )
          as _i5.Future<_i6.Foyer?>);

  @override
  _i5.Future<int> save(_i6.Foyer? foyer) =>
      (super.noSuchMethod(
            Invocation.method(#save, [foyer]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> update(_i6.Foyer? foyer) =>
      (super.noSuchMethod(
            Invocation.method(#update, [foyer]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> delete(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<bool> exists() =>
      (super.noSuchMethod(
            Invocation.method(#exists, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [BudgetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBudgetService extends _i1.Mock implements _i13.BudgetService {
  MockBudgetService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<List<_i14.BudgetCategory>> getBudgetCategories({String? month}) =>
      (super.noSuchMethod(
            Invocation.method(#getBudgetCategories, [], {#month: month}),
            returnValue: _i5.Future<List<_i14.BudgetCategory>>.value(
              <_i14.BudgetCategory>[],
            ),
          )
          as _i5.Future<List<_i14.BudgetCategory>>);

  @override
  _i5.Future<String> createBudgetCategory(
    _i14.BudgetCategory? category, {
    bool? notify = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createBudgetCategory,
              [category],
              {#notify: notify},
            ),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #createBudgetCategory,
                  [category],
                  {#notify: notify},
                ),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<int> updateBudgetCategory(
    _i14.BudgetCategory? category, {
    bool? notify = true,
    _i14.BudgetCategory? oldCategory,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateBudgetCategory,
              [category],
              {#notify: notify, #oldCategory: oldCategory},
            ),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<String> deleteBudgetCategory(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBudgetCategory, [id]),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#deleteBudgetCategory, [id]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> syncBudgetWithPurchases(String? idFoyer, {String? month}) =>
      (super.noSuchMethod(
            Invocation.method(
              #syncBudgetWithPurchases,
              [idFoyer],
              {#month: month},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getMonthlyExpenseHistory(
    String? idFoyer,
    String? categoryName, {
    int? monthsBack = 12,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getMonthlyExpenseHistory,
              [idFoyer, categoryName],
              {#monthsBack: monthsBack},
            ),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<void> initializeDefaultCategories({String? month}) =>
      (super.noSuchMethod(
            Invocation.method(#initializeDefaultCategories, [], {
              #month: month,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> checkBudgetAlertsAfterPurchase(
    String? idFoyer,
    String? categoryName, {
    String? month,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #checkBudgetAlertsAfterPurchase,
              [idFoyer, categoryName],
              {#month: month},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> recalculateCategoryBudgets(
    String? idFoyer,
    double? newTotalBudget, {
    String? month,
    double? oldTotalBudget,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #recalculateCategoryBudgets,
              [idFoyer, newTotalBudget],
              {#month: month, #oldTotalBudget: oldTotalBudget},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>> getBudgetSummary({String? month}) =>
      (super.noSuchMethod(
            Invocation.method(#getBudgetSummary, [], {#month: month}),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, double>> calculateRecommendedBudget(String? idFoyer) =>
      (super.noSuchMethod(
            Invocation.method(#calculateRecommendedBudget, [idFoyer]),
            returnValue: _i5.Future<Map<String, double>>.value(
              <String, double>{},
            ),
          )
          as _i5.Future<Map<String, double>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> generateSavingsTips(
    String? idFoyer, {
    String? month,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateSavingsTips, [idFoyer], {#month: month}),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<Map<String, dynamic>> getSpendingHistory(
    String? idFoyer, {
    int? monthsBack = 6,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getSpendingHistory,
              [idFoyer],
              {#monthsBack: monthsBack},
            ),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> initializeRecommendedBudgets(
    String? idFoyer, {
    String? month,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #initializeRecommendedBudgets,
              [idFoyer],
              {#month: month},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i16.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get pendingOperations =>
      (super.noSuchMethod(Invocation.getter(#pendingOperations), returnValue: 0)
          as int);

  @override
  int get failedOperations =>
      (super.noSuchMethod(Invocation.getter(#failedOperations), returnValue: 0)
          as int);

  @override
  bool get isSyncing =>
      (super.noSuchMethod(Invocation.getter(#isSyncing), returnValue: false)
          as bool);

  @override
  bool get hasError =>
      (super.noSuchMethod(Invocation.getter(#hasError), returnValue: false)
          as bool);

  @override
  bool get syncEnabled =>
      (super.noSuchMethod(Invocation.getter(#syncEnabled), returnValue: false)
          as bool);

  @override
  bool get userConsent =>
      (super.noSuchMethod(Invocation.getter(#userConsent), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> enableSync({required bool? userConsent}) =>
      (super.noSuchMethod(
            Invocation.method(#enableSync, [], {#userConsent: userConsent}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> disableSync() =>
      (super.noSuchMethod(
            Invocation.method(#disableSync, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> forceSyncWithFeedback(_i17.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#forceSyncWithFeedback, [context]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void showSyncErrorDialog(_i17.BuildContext? context) => super.noSuchMethod(
    Invocation.method(#showSyncErrorDialog, [context]),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> getSyncStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getSyncStatus, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i5.Future<void> enqueueOperation({
    required String? operationType,
    required String? entityType,
    required int? entityId,
    required Map<String, dynamic>? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#enqueueOperation, [], {
              #operationType: operationType,
              #entityType: entityType,
              #entityId: entityId,
              #payload: payload,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> cleanupSyncedOperations() =>
      (super.noSuchMethod(
            Invocation.method(#cleanupSyncedOperations, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> backgroundSync() =>
      (super.noSuchMethod(
            Invocation.method(#backgroundSync, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i18.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<bool> exchangeCodeForSession(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#exchangeCodeForSession, [code]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> resendConfirmationEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resendConfirmationEmail, [email]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> signUp({
    required String? email,
    required String? password,
    required String? firstName,
    required String? lastName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #password: password,
              #firstName: firstName,
              #lastName: lastName,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i3.AuthResponse> signUpWithEmail({
    required String? email,
    required String? password,
    required String? fullName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmail, [], {
              #email: email,
              #password: password,
              #fullName: fullName,
            }),
            returnValue: _i5.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_1(
                this,
                Invocation.method(#signUpWithEmail, [], {
                  #email: email,
                  #password: password,
                  #fullName: fullName,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.AuthResponse>);

  @override
  _i5.Future<bool> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i3.AuthResponse> signInWithEmail({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmail, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i5.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_1(
                this,
                Invocation.method(#signInWithEmail, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.AuthResponse>);

  @override
  _i5.Future<bool> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> resetPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [email]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> updateProfile({String? firstName, String? lastName}) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #firstName: firstName,
              #lastName: lastName,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i19.UserProfile?> getUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, []),
            returnValue: _i5.Future<_i19.UserProfile?>.value(),
          )
          as _i5.Future<_i19.UserProfile?>);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int?> getAppUserId() =>
      (super.noSuchMethod(
            Invocation.method(#getAppUserId, []),
            returnValue: _i5.Future<int?>.value(),
          )
          as _i5.Future<int?>);

  @override
  _i5.Future<String?> ensureHouseholdExists() =>
      (super.noSuchMethod(
            Invocation.method(#ensureHouseholdExists, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<bool> refreshSession() =>
      (super.noSuchMethod(
            Invocation.method(#refreshSession, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  bool isSessionExpired() =>
      (super.noSuchMethod(
            Invocation.method(#isSessionExpired, []),
            returnValue: false,
          )
          as bool);

  @override
  Map<String, dynamic> getStats() =>
      (super.noSuchMethod(
            Invocation.method(#getStats, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<bool> signInWithOAuth(_i3.OAuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithOAuth, [provider]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
